### ISSUE TITLE
Develop ADC Example

### ISSUE THREAD

**Issue by Vinimuller** [Vinimuller/Examples-STM32L0#1]
Implement a routine that reads the internal reference voltage and internal temperature sensor. The  internal reference voltage must be in millivolts and the temperature in Celsius.

We would like to have three versions of this code: Using ADC with polling, ADC with interrupts and ADC with DMA.

**Comment by rodrigocelmer** [comment]
Solved polling example with PR #6

**Comment by rodrigocelmer** [comment]
Solved interrupt example with PR #7

**Comment by rodrigocelmer** [comment]
Solved DMA example with PR #9
