### ISSUE TITLE
Develop PWR example

### ISSUE THREAD

**Issue by Vinimuller** [Vinimuller/Examples-STM32L0#3]
This issue may result in two examples:
1. Implement a code that when the button is pressed, the microcontroller enters in stop mode. After entering stop mode, the same button must wake up the microprocessor.
2. Implement a code that when the button is pressed, the microcontroller enters in stop mode and wakes up via RTC after 30 seconds.

**Comment by rodrigocelmer** [comment]
Item number 1 solved with PR #10

**Comment by rodrigocelmer** [comment]
Item number 2 solved with PR #11
