### ISSUE TITLE
Develop USART example

### ISSUE THREAD

**Issue by Vinimuller** [Vinimuller/Examples-STM32L0#4]
Implement a code that set up USART as asynchronous, no parity bit, 8 data bits and 115200 baudrate.
We may divide this task in some steps:
**Hardware Setup:**
Connect PB6 to Debbuger RX and PB7 to Debbuger TX. 
**Software Dev:**
1. Configure USART1 to operate with 115200, 8 data bits, no parity bit, 1 stop bit;
2. Write a simple code that sends something via serial; You must be able to see the data on the serial terminal.
3. Write a code that when it receives one letter, sends back the next letter on the alphabet;
4. Implement the printf function e rout its output to USART1.

**Comment by rodrigocelmer** [comment]
Issue solved with PR #8

**Comment by Vinimuller** [comment]
@rodrigocelmer Don't forget to close the PR and also the issue if it has been solved
